import { Provider } from "@/components/ui/provider";
import { InterestGuard } from "@/components/InterestGuard";
import { DemoSwitcher } from "@/components/DemoSwitcher";
import type { Metadata } from "next";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body>
        <Provider>
          <InterestGuard>
            {children}
          </InterestGuard>
          <DemoSwitcher />
        </Provider>
      </body>
    </html>
  );
}

